### ISSUE TITLE
Few things outstanding to get to an A+ 

### ISSUE THREAD

**Issue by firasm** [ubco-W2022T2-data301/project-group-group06#24]
Hello,

@sairafurqan and I are going through your project and you have met all but two of the criteria for an A+. One of the things is really easy, and the other one is slightly more involved. 

Here are the two things missing:

- [x] Issues aren't closed (though all the tasks are completed) ; effective use of issues requires all resolved issues to be closed.
- [x] Upon closer look, we haven't seen evidence of the "complex method chaining" criteria:

> Complex method chaining
> - At least three advanced operations (for e.g anonymous or lambda functions in assign or apply functions)
> - At least two method chains

At the moment, we're leaning towards downgrading your project to an **A**, but if you can fix these things before April 24th, we can award you your contracted grade of an A+.

Of course, you are more than welcome to just accept the **A**, but please let us know either way what you decide.

Thanks,

Dr. Moosvi

**Comment by ailieeeee** [comment]
All issues resolved for contracted grade A+.
